_wandb:
    value:
        cli_version: 0.23.1
        e:
            rvy4yjxygd9cdbwjhfoboo7upqntayw0:
                cpu_count: 64
                cpu_count_logical: 64
                disk:
                    /:
                        total: "76817485824"
                        used: "7812222976"
                email: s253819@dtu.dk
                executable: /zhome/8a/1/224071/code/MLOPS_105/.venv/bin/python3
                git:
                    commit: eb3da5226e86a67f5438aa5b5beb13775ce3dece
                    remote: https://github.com/ariansumak/MLOPS_105.git
                host: gbarlogin1
                memory:
                    total: "1081355767808"
                os: Linux-6.1.159-1.el9.elrepo.x86_64-x86_64-with-glibc2.34
                program: -m pneumoniaclassifier.train
                python: CPython 3.13.11
                root: /zhome/8a/1/224071/code/MLOPS_105
                startedAt: "2026-01-12T14:52:08.038152Z"
                writerId: rvy4yjxygd9cdbwjhfoboo7upqntayw0
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 1
                - 41
                - 50
            "2":
                - 1
                - 41
                - 50
            "3":
                - 1
                - 16
                - 61
            "4": 3.13.11
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
data:
    value:
        _target_: pneumoniaclassifier.data.get_dataloaders
        augment: true
        batch_size: 16
        data_dir: /zhome/8a/1/224071/data/kaggle/chest-xray-pneumonia/chest_xray
        num_workers: 2
eval:
    value:
        interval_steps: 200
        run_at_epoch_end: true
model:
    value:
        name: efficientnet_b0
        num_classes: 2
        pretrained: true
        unfreeze_blocks: 0
optimizer:
    value:
        _target_: torch.optim.Adam
        lr: 0.0001
        weight_decay: 0.0001
train:
    value:
        device: auto
        epochs: 5
        log_interval_steps: 50
        output_dir: reports
        seed: 42
wandb:
    value:
        enabled: true
        entity: null
        log_model: true
        project: pneumoniaclassifier
        run_name: null
