model:
  name: efficientnet_b0
  num_classes: 2
  pretrained: false
  artifact_path: s253819-danmarks-tekniske-universitet-dtu-org/wandb-registry-pneumonia_models/models:production

wandb:
  project: pneumoniaclassifier
  entity: s253819-danmarks-tekniske-universitet-dtu

inference:
  device: auto
  class_names:
    - NORMAL
    - PNEUMONIA
  image_size: 224
  mean:
    - 0.485
    - 0.456
    - 0.406
  std:
    - 0.229
    - 0.224
    - 0.225
