model:
  name: efficientnet_b0
  num_classes: 2
  pretrained: false
  checkpoint_path: models/m22_model.pt

inference:
  device: auto
  class_names:
    - NORMAL
    - PNEUMONIA
  image_size: 224
  mean:
    - 0.485
    - 0.456
    - 0.406
  std:
    - 0.229
    - 0.224
    - 0.225
