receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "pneumonia-api"
          scrape_interval: 10s
          static_configs:
            - targets: ["localhost:8000"]
exporters:
  googlecloud:
    metrics:
      prefix: "custom.googleapis.com/"
service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [googlecloud]
