workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: europe-west1-docker.pkg.dev/pneuomonia-classifier/docker-registry/train
        env:
        - name: WANDB_API_KEY
          value: $WANDB_API_KEY