workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: gcr.io/pneumonia-classifier/train
        env:
        - name: WANDB_API_KEY
          value: $WANDB_API_KEY